In [ ]:
"""Q1. What is a database? Differentiate between SQL and NoSQL databases.
Ans.: A database is a structured collection of data that is organized in a way that allows it to be easily managed, accessed, and updated. Databases 
are commonly used in many different applications, including business, scientific research, and entertainment.

SQL and NoSQL are two different types of databases that use different approaches to storing and retrieving data.

SQL (Structured Query Language) databases are relational databases that use tables to store and organize data. These databases use SQL to manage and
manipulate the data. SQL databases are highly structured, and data is stored in a way that makes it easy to search, sort, and analyze. SQL databases
are best suited for applications that require complex queries and transactions, such as financial systems or e-commerce sites.

NoSQL (Not Only SQL) databases are non-relational databases that use a variety of data models, such as key-value pairs, documents, and graphs, to 
store data. NoSQL databases are highly scalable and flexible, and can handle large volumes of unstructured or semi-structured data. NoSQL databases 
are best suited for applications that require fast and efficient data processing, such as social media platforms or real-time analytics systems.

In summary, SQL databases are highly structured and best suited for applications that require complex queries and transactions, while NoSQL databases 
are highly scalable and flexible, and best suited for applications that require fast and efficient data processing.
"""

In [ ]:
"""Q2. What is DDL? Explain why CREATE, DROP, ALTER, and TRUNCATE are used with an example.
Ans.:DDL stands for Data Definition Language, which is a set of SQL commands used to define and manage the structure of a database. DDL commands 
are used to create, modify, and delete database objects such as tables, indexes, and views.

The following are some common DDL commands and their purposes:

1. CREATE: This command is used to create new database objects such as tables, views, and indexes. For example, the following SQL command creates 
a new table named "customers" with columns for customer name, email, and phone number:
    
    CREATE TABLE customers (
  customer_id INT PRIMARY KEY,
  customer_name VARCHAR(50),
  email VARCHAR(50),
  phone VARCHAR(20)
);

2. DROP: This command is used to delete existing database objects such as tables, views, and indexes. For example, the following SQL command drops 
the "customers" table:

    DROP TABLE customers;

3. ALTER: This command is used to modify the structure of existing database objects such as tables, views, and indexes. For example, the following 
SQL command adds a new column named "address" to the "customers" table:

    ALTER TABLE customers ADD address VARCHAR(100);

4. TRUNCATE: This command is used to delete all the data from a table, while keeping its structure intact. For example, the following SQL command 
deletes all the data from the "customers" table:

    TRUNCATE TABLE customers;

"""

In [ ]:
"""Q3. What is DML? Explain INSERT, UPDATE, and DELETE with an example.
Ans.: DML stands for Data Manipulation Language, which is a set of SQL commands used to manipulate the data within a database. DML commands are used 
to insert, update, and delete data within tables.
The following are some common DML commands and their purposes:

1. INSERT: This command is used to insert new data into a table. For example, the following SQL command inserts a new record into the "customers" 
table:

    INSERT INTO customers (customer_id, customer_name, email, phone)
    VALUES (1, 'John Doe', 'john.doe@example.com', '123-456-7890');
    
2. UPDATE: This command is used to update existing data within a table. For example, the following SQL command updates the phone number of the 
customer with ID 1:
    
    UPDATE customers
    SET phone = '555-555-5555'
    WHERE customer_id = 1;
    
3. DELETE: This command is used to delete data from a table. For example, the following SQL command deletes the record for the customer with ID 1:

    DELETE FROM customers
    WHERE customer_id = 1;


"""

In [ ]:
"""Q4. What is DQL? Explain SELECT with an example.
Ans.: DQL stands for Data Query Language, which is a set of SQL commands used to retrieve data from a database. DQL commands are used to query and 
retrieve data from tables.

The most common DQL command is SELECT, which is used to retrieve data from one or more tables based on certain conditions. Here is an example of 
how SELECT can be used:

Suppose we have a table called "employees" with columns for employee ID, name, department, and salary. We can use SELECT to retrieve the names 
and salaries of all employees in the "sales" department who earn more than $50,000 per year. Here is the SQL command:
    
    SELECT name, salary
    FROM employees
    WHERE department = 'sales' AND salary > 50000;
    
This command specifies that we want to select the "name" and "salary" columns from the "employees" table where the "department" column is equal to 
"sales" and the "salary" column is greater than 50,000. The results of this query will be a table with two columns: "name" and "salary", and the rows
will contain the names and salaries of all employees in the "sales" department who earn more than $50,000 per year.

In summary, SELECT is a DQL command used to retrieve data from a database based on certain conditions. It allows us to query the database and retrieve 
only the data we need. """

In [ ]:
"""Q5. Explain Primary Key and Foreign Key.
Ans.: Primary key and foreign key are two important concepts in relational database design.

A primary key is a column or set of columns in a table that uniquely identifies each row in that table. The primary key must be unique for each row 
and cannot contain null values. The primary key is used to enforce data integrity and ensure that there are no duplicate rows in the table. 
For example, in a table of employees, the primary key could be the employee ID, which uniquely identifies each employee.

A foreign key is a column or set of columns in a table that refers to the primary key of another table. The foreign key establishes a relationship 
between the two tables, and it is used to ensure referential integrity between the tables. For example, in a table of orders, the customer ID column 
could be a foreign key that refers to the primary key of the customers table. This ensures that each order is associated with a valid customer.

In summary, a primary key is used to uniquely identify each row in a table, while a foreign key is used to establish a relationship between two tables
by referring to the primary key of another table. Together, primary and foreign keys are used to ensure data integrity and maintain consistency in a 
relational database."""

In [ ]:
"""Q6. Write a python code to connect MySQL to python. Explain the cursor() and execute() method.
Ans.:To connect MySQL to Python, we need to use a Python library called mysql-connector-python. Here is an example of how to connect to MySQL and 
execute a SQL command using Python:"""

import mysql.connector

# establish a connection to the database
mydb = mysql.connector.connect(
  host="localhost",
  user="username",
  password="password",
  database="databasename"
)

# create a cursor object
mycursor = mydb.cursor()

# execute a query
mycursor.execute("SELECT * FROM customers")

# fetch the results
results = mycursor.fetchall()

# print the results
for row in results:
  print(row)
        
"""In this code, we first import the "mysql.connector" module to establish a connection to the database. We then use the "connect()" method to
establish a connection by passing in the host, username, password, and database name as arguments.

Next, we create a cursor object using the "cursor()" method. The cursor object allows us to execute SQL queries on the database and fetch the 
results. The cursor object is created from the connection object we created earlier.


We then execute a query using the "execute()" method of the cursor object. This method takes an SQL query as an argument and executes it on the 
database. In this example, we are selecting all rows from the "customers" table.

After executing the query, we fetch the results using the "fetchall()" method of the cursor object. This method returns all the rows that were 
returned by the query.

Finally, we print the results by looping through each row returned by the query."""

In [ ]:
"""Q7. Give the order of execution of SQL clauses in an SQL query.
Ans.: The order of execution of SQL clauses in an SQL query is as follows:

FROM - The FROM clause specifies the table or tables from which data will be retrieved.

WHERE - The WHERE clause filters the data based on certain conditions.

GROUP BY - The GROUP BY clause is used to group the data based on one or more columns.

HAVING - The HAVING clause filters the grouped data based on certain conditions.

SELECT - The SELECT clause retrieves the data from the table(s) based on the specified columns.

DISTINCT - The DISTINCT keyword is used to remove duplicate rows from the results.

ORDER BY - The ORDER BY clause sorts the data based on one or more columns.

LIMIT - The LIMIT clause is used to limit the number of rows returned by the query.